version: '2'
services:

  # The Application
  app:
    build: 
      context: .
      dockerfile: Docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./Docker/certs:/home/certs
      - ./www:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build: 
      context: .
      dockerfile: Docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80
      - 443:443
    links:
      - app
    depends_on:
      - app

volumes:
  dbdata: